# Generated by Django 4.2.2 on 2023-07-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deportistas', '0004_representante_deportista_nombre_representante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deportista',
            old_name='nombre_representante',
            new_name='representante',
        ),
        migrations.RenameField(
            model_name='representante',
            old_name='nombre_representante',
            new_name='nombre',
        ),
    ]
