# Generated by Django 4.2.2 on 2023-07-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportistas', '0005_rename_nombre_representante_deportista_representante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representante',
            name='nombre',
        ),
        migrations.AddField(
            model_name='representante',
            name='nombre_representante',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
